Update the library view to include downloading
Aidoku/Aidoku pull request #185
Opened 2023-02-26 02:41 UTC by zabroseric

2023-02-26 02:46 UTC, zabroseric commented
Example of UI
<img width="445" alt="image" src="https://user-images.githubusercontent.com/8380607/221389325-1b7a6116-4e5d-4ccb-a5a0-cf822624a8b2.png">

Note: I'm a React / NodeJS dev, so feel free to request corrections to better follow project/language standards.

2023-02-26 14:36 UTC, Skittyblock requested changes
might as well set the two download functions as `async` rather than spawning a task inside them and then instead spawn a task when you call them

2023-02-26 14:36 UTC, Skittyblock commented on iOS/Scenes/Library/LibraryViewController.swift
> +            let chapters = ((try? await source?.getChapterList(manga: manga)) ?? []).filter {
probably best to use `CoreDataManager.shared.getChapters` instead https://github.com/Aidoku/Aidoku/blob/d19878092bfe2168d95e7a234b743d55d320580e/Shared/Managers/CoreData/CoreDataManager%2BChapter.swift#L51

2023-03-02 06:21 UTC, zabroseric commented
Awesome, thanks @Skittyblock for the info, especially considering it would just be quicker for
you to resolve it yourself. I've fixed what you mentioned, and it makes sense. It feels like the download functionality (all/unread) should be moved out of the controller, and into something like the DownloadManager. Thoughts?

2023-03-02 06:23 UTC, zabroseric commented on iOS/Scenes/Library/LibraryViewController.swift
> +            readingHistory[$0.id] == nil || readingHistory[$0.id]?.page != -1
Ensure partially, but unread chapters are downloaded.

2023-03-04 03:51 UTC, Skittyblock commented
yeah might be good to add the functions to `DownloadManager` instead since I might add an option in the manga menu for downloading (like unread and ranges, etc.)

2023-03-05 01:33 UTC, zabroseric commented
Sweet, that change has been made. Yeah, I was thinking the same and played around with the idea below:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/8380607/222936761-337dff58-cf0b-4ce0-a6ca-19ca1f5642d4.png">

2023-03-05 02:43 UTC, Skittyblock commented
I would probably just do a child menu in the ellipsis menu rather than a popover but yeah

2023-03-05 02:44 UTC, Skittyblock approved these changes

2023-03-05 03:16 UTC, zabroseric commented
Sweet, your project, your call. :)

2023-03-23 19:19 UTC, merged