[slider] add haptic feedback when slider changes page
Aidoku/Aidoku pull request #248
Opened 2023-06-04 04:07 UTC by annuhdo

# Context
Issue: https://github.com/Aidoku/Aidoku/issues/191

- Added selection haptic feedback when `ReaderViewController#displayPage` gets called.
- Stored `currentPageLabelVal` to `ReaderToolbarView.swift` so we can figure out if the user had slid to a page that differed from previous page. We only fire the haptic feedback when the page changes.

# Test
- Can't build this on physical device so I can't really test.
- Ran print statements which ran in the if block.

----

I'm new to iOS development so would appreciate any feedback! I'm also aware that the test plan is lacking so feel free to reject the PR but pls provide feedback on code if possible :)

2023-06-07 16:45 UTC, ItsLame commented
Just tested it on my iPhone. Rather than the haptic feedback kicking in when page changes, it instead continuously triggers haptic when dragging the slider.

2023-06-07 16:51 UTC, annuhdo commented
@ItsLame oof. Let me try again and test on a test project.

Not familiar with how to set this PR as planning changes but uh —planning changes— now.

2023-06-07 19:42 UTC, annuhdo commented
Will put up another PR

2023-06-07 19:46 UTC, ItsLame commented
@annuhdo I think you can just make updates to your current branch (`hapticslider`) and it'll show up here

2023-06-07 19:52 UTC, ItsLame commented
> Not familiar with how to set this PR as planning changes but uh —planning changes— now.

Also for this I usually just set the PR back to draft like so:
![image](https://github.com/Aidoku/Aidoku/assets/37344470/ae1bc69d-094c-488e-829f-435aebb3d7b1)

2023-07-24 11:58 UTC, ItsLame commented
@annuhdo just noticed, I think you forgot to re-open this PR?

2023-08-06 23:20 UTC, Skittyblock requested changes

2023-08-06 23:20 UTC, Skittyblock commented on iOS/UI/Reader/ReaderToolbarView.swift
> +        }
you don't need two variables, just use `oldValue`
```suggestion
            if oldValue != currentPageValue {
                let feedbackGenerator = UISelectionFeedbackGenerator()
                feedbackGenerator.selectionChanged()
            }
        }
```

2023-08-27 02:50 UTC, merged