Download with Wi-Fi only
Aidoku/Aidoku pull request #394
Opened 2024-01-21 18:59 UTC by urbaneewe

Added the toggle in the settings to download with Wi-Fi only.
Also added the alerts if the user tries to download while not on Wi-Fi.

Closes #348

2024-01-23 10:17 UTC, Skittyblock requested changes
here are a few style changes.

I'll check out the functionality later, but I think it might be a good idea to add in the hanging downloads when disconnected from wifi before this is merged. it should be as simple as just checking if the setting is on and if wifi isn't connected whenever it tries to move on to a new download

2024-01-23 10:17 UTC, Skittyblock commented on iOS/UI/Manga/MangaViewController.swift
> +            preferredStyle: .alert)
```suggestion
            preferredStyle: .alert
        )
```

2024-01-23 10:17 UTC, Skittyblock commented on iOS/UI/Manga/MangaViewController.swift
> +        present(alertController, animated: true, completion: nil)
I don't think you need the completion parameter since it defaults to nil
```suggestion
        present(alertController, animated: true)
```

2024-01-23 10:17 UTC, Skittyblock commented on iOS/UI/Manga/MangaViewController.swift
> +//                    DownloadManager.shared.download(chapters: [chapter], manga: self.manga)
```suggestion
```

2024-01-23 10:17 UTC, Skittyblock commented on iOS/UI/Library/LibraryViewController.swift
> +
```suggestion
```

2024-01-28 21:50 UTC, urbaneewe commented
@Skittyblock Hey Skitty. Couple of questions and some possible improvements before I make more commits.

- When there are multiple downloads in the queue and the wifi suddenly cuts do we just cancel all the downloads and show an alert?

- Besides canceling I have 2 suggestions: Storing the downloads or simply pausing them. I see some beginnings of the code for both suggestions but I'm not sure how you planned to integrate it. For now I can just cancel the downloads if you don't want these implemented

- Also I may have found a solution for the multiple declarations of the `showNoWifiAlert` function. I was thinking I can change the definitions of the download methods in the `DownloadManager` to include an `@escaping` closure that contains the alert. That way whenever the function is called we can pass whatever we want for the alert.

2024-01-29 12:22 UTC, Skittyblock commented
Ideally, downloads should be paused instead of cancelled. Then there should be a button to resume that will show an alert instead of actually resuming if you're not on wifi and you have the setting enabled.

I'm not sure exactly what you mean about adding a closure to `DownloadManager` methods. Do you mean like a completion handler? That isn't necessary since it's async. Do you mean to include the actual alert in the method and then pass the contents or action or whatever to it in the arguments? I'd prefer to not do that since it's a shared manager that should be platform agnostic (e.g. doesn't have any ui code like alerts).

2024-05-04 07:51 UTC, Skittyblock requested changes

2024-05-04 07:51 UTC, Skittyblock commented on iOS/UI/Library/LibraryViewController.swift
there should be a way to decrease the amount of code duplication here since you're doing essentially the same thing like 4 time, but honestly it's whatever since I know this stuff will be rewritten eventually.

2024-05-04 08:41 UTC, urbaneewe commented on iOS/UI/Library/LibraryViewController.swift
Probably leave it like this for now since I don't know what your plans for rewriting are.
I've pulled out the alert creation logic in a separate extension.

One thing that comes to mind here would be to have an `enum` for different download actions (all, unread) and then we would only need one check of the settings with the `switch/case` doing the task of calling the right method

2024-05-05 02:30 UTC, Skittyblock requested changes
Alright the only issue I see is you can't tell easily when downloads are paused. I think I would, instead of doing a menu with clear and pause/resume buttons, just put the two buttons on the left side of the navbar, and then people can see if it's paused without having to open the menu. But if you have a better idea that'd be fine.

2024-05-05 02:30 UTC, Skittyblock commented on Aidoku.xcodeproj/project.pbxproj
> +
```suggestion
```

2024-05-05 08:41 UTC, urbaneewe commented
> Alright the only issue I see is you can't tell easily when downloads are paused. I think I would, instead of doing a menu with clear and pause/resume buttons, just put the two buttons on the left side of the navbar, and then people can see if it's paused without having to open the menu. But if you have a better idea that'd be fine.

Well, we had a discussion about this on Discord where you suggested the UIMenu because having two buttons one next to another looked ugly and we didn't want to do floating buttons because those are too Android like.

I don't really have an alternative suggestion here so I can do the buttons one next to another if you really want that

2024-05-05 23:19 UTC, Skittyblock requested changes
rest looks good to me

2024-05-05 23:19 UTC, Skittyblock commented on Shared/Extensions/UIViewController+Alerts.swift
> +        }
```suggestion
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)

        // If no actions are provided, add a default 'OK' action
        if actions.isEmpty {
            let okAction = UIAlertAction(title: NSLocalizedString("OK", comment: ""), style: .cancel)
            alertController.addAction(okAction)
        } else {
            for action in actions {
                alertController.addAction(action)
            }
        }

        self.present(alertController, animated: true, completion: completion)
    }
```

2024-05-05 23:19 UTC, Skittyblock commented on Shared/Extensions/UIViewController+Alerts.swift
This shouldn't be under the Shared folder since it's only for iOS, not cross platform

2024-05-12 03:30 UTC, Skittyblock commented on iOS/Extensions/UIViewController+Alerts.swift
> +            let okAction = UIAlertAction(title: NSLocalizedString("OK", comment: ""), style: .default)
```suggestion
            let okAction = UIAlertAction(title: NSLocalizedString("OK", comment: ""), style: .cancel)
```

2024-05-12 03:34 UTC, merged