Add warning message when chapters are being skipped
Aidoku/Aidoku pull request #457
Opened 2024-06-25 22:46 UTC by kanshres

Addresses issue #212 

Let me know if the text or styling should be changed. Maybe a warning icon should be displayed?

<img width="404" alt="image" src="https://github.com/Aidoku/Aidoku/assets/52114668/36b52cde-8e27-4d07-9408-3bda4729d994">

2024-07-04 16:08 UTC, Skittyblock requested changes
We should make it more like tachiyomi; have the number of chapters being skipped, use the `exclamationmark.triangle.fill` sf symbol with a yellow color (like the trackers page), and put it in between the finished and next groups (since we're skipping chapters between them).

You can probably have the label just in between the other labels in the stack view, and make sure the width is limited so it's word wrapped properly.

2024-07-11 20:23 UTC, kanshres commented
This is how it looks now:
<img width="377" alt="image" src="https://github.com/Aidoku/Aidoku/assets/52114668/7864af94-4d75-4ad9-8eb0-86f6aa20b551">

Tachiyomi for comparison:
![image](https://github.com/Aidoku/Aidoku/assets/52114668/b3d2612b-3811-44e2-b96f-70de460e7a3a)

2024-07-13 21:23 UTC, Skittyblock commented
wow thanks for making it just like I said... but now that I see it I feel like it's not quite right. maybe the warning icon should be above the text instead of next to it? you can probably leave it as-is and I'll take a look at it myself before I push the next update so we can get this merged before then, thanks

2024-08-11 00:53 UTC, Skittyblock approved these changes

2024-08-11 00:53 UTC, merged