Add action for clearing history excluding mangas in library
Aidoku/Aidoku pull request #459
Opened 2024-07-02 22:19 UTC by kanshres

This closes #210 

On the history tab, I added a new action for clearing all history outside of manga in the user's library.
<img width="396" alt="image" src="https://github.com/Aidoku/Aidoku/assets/52114668/db559fe5-63e3-416a-9167-a4cef7ea1853">

Should this new action be added to Settings on "Clear Read History"? Also, let me know if the string or anything else should be changed.

2024-07-04 16:14 UTC, Skittyblock commented
I think this is probably okay to have temporarily, but my actual plan was to have a page in settings that lists all the manga with history that aren't added to your library, and allows you to selectively delete them, or open them if you still have the source installed

2024-07-10 06:03 UTC, kanshres commented
> I think this is probably okay to have temporarily, but my actual plan was to have a page in settings that lists all the manga with history that aren't added to your library, and allows you to selectively delete them, or open them if you still have the source installed

Ah ok. Would that be a change for 0.7?

2024-07-13 21:20 UTC, Skittyblock commented
likely wont be in the initial 0.7 update since my goal is just to rewrite the source api and anything surrounding that which needs to be, but it would come after 0.7

2024-07-17 21:41 UTC, kanshres commented
Feel free to close this PR if you decide it's not needed

2024-08-11 00:20 UTC, Skittyblock requested changes
Actually yeah I think a better place for this would be in the advanced section in the settings tab, under the "Clear Reading History" option

2024-09-05 01:54 UTC, kanshres commented
> Actually yeah I think a better place for this would be in the advanced section in the settings tab, under the "Clear Reading History" option

I've made the changes. Should the history be reloaded after clearing? I noticed it's done so in HistoryViewController but not in SettingsViewController

2024-09-16 14:00 UTC, Skittyblock commented
> Should the history be reloaded after clearing? I noticed it's done so in HistoryViewController but not in SettingsViewController

Is there a notification key for it? I can't remember. It probably should be, but depends on what you see while testing. If you open the history tab, then settings and clear history, then go back to the history tab, does it still display stuff?
I would assume it also needs to update all the badges in library as well.

2024-09-19 07:13 UTC, kanshres commented
> > Should the history be reloaded after clearing? I noticed it's done so in HistoryViewController but not in SettingsViewController
> 
> Is there a notification key for it? I can't remember. It probably should be, but depends on what you see while testing. If you open the history tab, then settings and clear history, then go back to the history tab, does it still display stuff? I would assume it also needs to update all the badges in library as well.

Yeah when I do the normal history clear, the items in the history tab are still there

2024-09-22 17:55 UTC, Skittyblock requested changes
so yeah, add the notification sending to refresh the history tab and this should be good

2025-01-31 03:47 UTC, kanshres commented
I added the notification to normal clear and the new clear without library items in Settings

2025-02-06 16:21 UTC, Skittyblock approved these changes
lgtm, i'll get it in before the next update

2025-03-25 02:16 UTC, merged